services:
  db:
    image: postgres
    container_name: ${POSTGRES_CONTAINER}
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata-ethereum:/var/lib/postgresql/data 
    ports: 
      - 5432:${POSTGRES_PORT}
 
 
volumes:
  pgdata-ethereum: