DROP TABLE IF EXISTS dynamic_configuration CASCADE;

CREATE TABLE dynamic_configuration(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    created_at timestamp,
    updated_at timestamp
);